// ? PAGES
export { ErrorPage } from './error/ErrorPage'
export { HomePage } from './home/HomePage'
export { LayoutPages } from './layout/LayoutPages'
export { LoginPage } from './login/LoginPage'
export { RegisterPage } from './register/RegisterPage'
export { Mujer } from './mujer/Mujer'
export { ProfilePage } from './profile/ProfilePage'
export { OrderPage } from './order/OrderPage'
export { PaymentsPage } from './payments/PaymentsPage'
export { RecoveryPassword } from './recovery/RecoveryPassword'
export { MayoristaPage } from './mayorista/MayoristaPage'
export { HombrePage } from './hombre/HombrePage'
export { MujerPage } from './mujer/MujerPage'
